import sqlite3
import os
import sys
import time

# Ensure we can import generated proto
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

try:
    import ecommerce_pb2
except ImportError:
    print("Please run 'protoc --python_out=. ecommerce.proto' first.")
    sys.exit(1)

def main():
    db_file = "ecommerce.db"
    
    # Clean up old DB if exists
    if os.path.exists(db_file):
        os.remove(db_file)
        
    conn = sqlite3.connect(db_file)
    
    # Load extension
    conn.enable_load_extension(True)
    try:
        # Assuming we run from the 'example' directory
        conn.load_extension("../lite_proto.so")
        print("Loaded lite_proto extension successfully.")
    except sqlite3.OperationalError as e:
        print(f"Failed to load extension: {e}")
        print("Make sure you have built lite_proto.so in the parent directory.")
        sys.exit(1)
        
    # Create base table
    conn.execute("""
    CREATE TABLE orders_base (
        id TEXT PRIMARY KEY,
        pb_blob BLOB
    )
    """)
    
    # Helper to create an order
    def create_order(oid, cid, amount, status):
        order = ecommerce_pb2.Order()
        order.id = oid
        order.customer_id = cid
        order.total_amount = amount
        order.status = status
        order.created_at = int(time.time())
        order.updated_at = int(time.time())
        return order
        
    # Insert sample data (Create)
    orders = [
        create_order("ORD001", "CUST01", 100.50, 1),
        create_order("ORD002", "CUST02", 50.00, 2),
        create_order("ORD003", "CUST01", 250.00, 1),
    ]
    
    for o in orders:
        conn.execute("INSERT INTO orders_base (id, pb_blob) VALUES (?, ?)", (o.id, o.SerializeToString()))
    conn.commit()
    print(f"Inserted {len(orders)} sample orders into orders_base.")
    
    # Create virtual table
    # We need to provide the schema file and message name
    # We assume 'ecommerce.pb' exists (generated by protoc --descriptor_set_out)
    conn.execute("CREATE VIRTUAL TABLE orders USING lite_proto('ecommerce.pb', 'Order', 'orders_base', 'pb_blob')")
    print("Created virtual table 'orders'.")
    
    # Query 1: Full scan via virtual table (Read)
    print("\n--- Querying via Virtual Table ---")
    cursor = conn.execute("SELECT id, customer_id, total_amount, status FROM orders")
    for row in cursor:
        print(f"Order: {row[0]}, Customer: {row[1]}, Amount: {row[2]}, Status: {row[3]}")
        
    # Query 2: Using proto_extract
    print("\n--- Querying via proto_extract ---")
    cursor = conn.execute("SELECT id, proto_extract(pb_blob, 'ecommerce.pb', 'Order', 'total_amount') FROM orders_base WHERE id = 'ORD001'")
    for row in cursor:
        print(f"Order: {row[0]}, Amount (extracted): {row[1]}")
        
    # Demonstrate Update
    print("\n--- Demonstrating Update on Base Table ---")
    # Read, modify, write back
    cursor = conn.execute("SELECT pb_blob FROM orders_base WHERE id = 'ORD002'")
    blob = cursor.fetchone()[0]
    order = ecommerce_pb2.Order()
    order.ParseFromString(blob)
    print(f"Original Status of ORD002: {order.status}")
    
    order.status = 3 # Shipped
    order.updated_at = int(time.time())
    
    conn.execute("UPDATE orders_base SET pb_blob = ? WHERE id = ?", (order.SerializeToString(), "ORD002"))
    conn.commit()
    
    # Verify via virtual table
    cursor = conn.execute("SELECT id, status FROM orders WHERE id = 'ORD002'")
    row = cursor.fetchone()
    print(f"Updated Status of ORD002 (via vtab): {row[1]}")
    
    # Demonstrate Upsert
    print("\n--- Demonstrating Upsert on Base Table ---")
    new_order = create_order("ORD002", "CUST02", 75.00, 1) # Same ID, different data
    
    conn.execute("""
    INSERT INTO orders_base (id, pb_blob) VALUES (?, ?)
    ON CONFLICT(id) DO UPDATE SET pb_blob = excluded.pb_blob
    """, (new_order.id, new_order.SerializeToString()))
    conn.commit()
    
    cursor = conn.execute("SELECT id, total_amount, status FROM orders WHERE id = 'ORD002'")
    row = cursor.fetchone()
    print(f"Upserted ORD002 (via vtab): Amount={row[1]}, Status={row[2]}")
    
    # Demonstrate Delete
    print("\n--- Demonstrating Delete on Base Table ---")
    conn.execute("DELETE FROM orders_base WHERE id = 'ORD001'")
    conn.commit()
    
    cursor = conn.execute("SELECT id FROM orders")
    rows = cursor.fetchall()
    print(f"Remaining orders after delete: {[r[0] for r in rows]}")
    
    conn.close()

if __name__ == "__main__":
    main()
